openapi: 3.0.3
info:
  title: StarshipOrderService API
  version: 1.0.0
  description: API для заказа деталей космического корабля
x-ogen:
  package: order_v1
  clean: true

tags:
  - name: Order
    description: Обработка заказов деталей для космического корабля

paths:
  /api/v1/orders:
    $ref: ./paths/order_create.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/order_by_uuid.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml