services:

  mongo-inventory:
    image: mongo:7.0.5
    container_name: mongo-inventory

    env_file:
      - .env

    volumes:
      - mongo_inventory_data:/data/db

    ports:
      - ${MONGO_PORT}:27017

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongo --eval \"db.stats()\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    
    restart: unless-stopped

    networks:
      - microservices-net

volumes:
  mongo_inventory_data:

networks:
  microservices-net:
    external: true